# Stage 1: Build React/Vite app
FROM node:18 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve with Tomcat
FROM tomcat:9-jdk17
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build-stage /app/dist /usr/local/tomcat/webapps/ecommerce
EXPOSE 8082
CMD ["catalina.sh", "run"]
