version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: s109-db
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "8083:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "8082:8080"
    depends_on:
      - backend

volumes:
  db_data:
